## 这时一个实例代码请根据你情况配置功能.如果不能直接访问github 请替换下面的url改为镜像地址
ikuai-url: http://192.168.10.1 # 爱快网页控制台登陆地址 结尾不要加 "/"，
username: admin # ikuai username 爱快登陆用户名
password: admin@123 # ikuai user password爱快登陆密码
cron: 0 5 * * * # crontab 执行更新的周期 格式为linux crontab 格式 注意时区问题，也可以用  @every 24h00m00s  表示每间隔24小时执行一次 openwrt可能需要处理时区 https://github.com/joyanhui/ikuai-bypass/issues/33
AddErrRetryWait: 10s # 自动重试时间间隔 时间格式为 10s  120s
AddWait: 1s # 添加规则后等待时间 等待爱快反应 适合性能低的设备

ip-group: # IP分组 和端口分流配合使用
  - name: 国内 # IP分组名称，分为多个时在名称后面拼接“序号”，如“国内_1”  因为爱快的ip分组没有备注功能，这里使用  IKUAI_BYPASS_<国内>_<01>来区分，
    # 为了实现先增加后删除，因爱快的分组增加时分组名称不能有同名的存在，所以在最后增加了4位数字作后缀，如“国内_12_1234”,分组名最大20个字条，减去占用的字符，这里的名称最多12个字符。
    ## IP分组 cidr 列表网址，每行一个，超过1000行会自动分为多个，ipv6 地址会被删除
    url: https://gh-proxy.com/raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt

stream-ipport: # 端口分流，与IP分组组合使用
  - type: 0 # 分流方式：0-外网线路，1-下一跳网关
    interface: wan1 # 分流线路 这里默认到wan1 运营商
    src-addr: 192.168.10.10-192.168.10.249 # 分流的源地址  对应 ip-group: 国内 的目标地址
    ip-group: 国内


custom-isp: # 自定义运营商  IP分流
  - name: 国内IP列表 # 自定义运营商名称
    url: https://gh-proxy.com/raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
    tag: ipcn # 规则的备注标签后缀 如果留空默认为自定义运营商名称
  - name: telegram
    url: https://gh-proxy.com/raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt
    tag: iptg
  - name: google
    url: https://gh-proxy.com/raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt
    tag: ipgoogle


stream-domain: # 域名分流 可选功能，优先级比ip分流高
  #- interface: wan2 # 分流线路
  #  src-addr: 192.168.10.10-192.168.10.249    # 分流的源地址 多ip段用“,”分开 参考 https://github.com/joyanhui/ikuai-bypass/issues/1#issuecomment-1892763993
  #  ## 域名列表网址，每行一个，超过1000行会自动分为多个
  #  url:  https://gh-proxy.com/raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt
  # 下面是强制走wan2的

  - interface: wan2
    src-addr: 192.168.10.10-192.168.10.249
    # 强制走代理的域名
    url: https://gh-proxy.com/raw.githubusercontent.com/lee99/clash-ruler/refs/heads/main/ikuai-bypass/bypass-domain-list.txt
    tag: private_bypass
  - interface: wan2
    src-addr: 192.168.10.10-192.168.10.249
    url: https://gh-proxy.com/raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt
    tag: gfw
    # 强制直连的，
  - interface: wan1
    src-addr: 192.168.10.10-192.168.10.249
    url: https://gh-proxy.com/raw.githubusercontent.com/lee99/clash-ruler/refs/heads/main/ikuai-bypass/direct-domain-list.txt
    tag: private_direct
